---
title: "Big Data"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(tidyverse)
```


```{r big_read, cache = TRUE}
# The real data does not have the same columns as the demo data. Very annoying!
# Note you can use the n_max argument to read_csv() to just read in the first
# 100 or so rows, thereby quickly getting back the message about the column
# types. Then, we use this new listing of types. Use cache = TRUE so that you
# don't have to repeat long calculations every time you reknit the document.

x <- read_csv("~/data/census/censoc_dmf_v2/censoc_dmf_v2.csv",
                   col_types = cols(HISTID = col_character(),
                                    byear = col_double(),
                                    bmonth = col_double(),
                                    dyear = col_double(),
                                    dmonth = col_double(),
                                    death_age = col_double(),
                                    link_abe_exact_conservative = col_double(),
                                    weight = col_double(),
                                    weight_conservative = col_double()))
```


```{r sample_1percent, cache = TRUE}

small <- x %>%
  slice_sample(prop = 0.01)

```

```{r barplot, cache = TRUE}

small_barplot <- small %>%
  ggplot(aes(x = dmonth)) +
  geom_bar()

small_barplot

```
```{r, jantojul}

bigdata_plot <-x %>%
  select(dmonth, dyear) %>%
  group_by(dmonth, dyear) %>% 
  summarize(sum_deaths = n(),
            .groups = "drop") %>%
  pivot_wider(names_from = dmonth,
              names_prefix = "dmonth_",
              values_from = sum_deaths) %>% 
  mutate(jan_jul_ratio = dmonth_1/dmonth_7) %>%
  select(dyear, dmonth_1, dmonth_7, jan_jul_ratio) %>%
  
  ggplot(mapping = aes(x = dyear,
                       y = jan_jul_ratio)) +
  geom_point() +
  geom_smooth(method = "lm",
              formula = y ~ x) +
  labs(title = "Mortality Over Time",
       subtitle = "Why are Januaries becoming more dangerous?",
       x = "Year of Death",
       y = "Ratio of January to July Deaths",
       caption = "Source: CenSoc")

bigdata_plot
# monthd, , dyear
```


